# small_flow/docker/airflow/Dockerfile.Base



FROM apache/airflow:2.9.2

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN FERNET_KEY=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())") && \
    echo "AIRFLOW__CORE__FERNET_KEY=$FERNET_KEY" >> /usr/local/airflow/.env

COPY ../../plugins /opt/airflow/plugins