# small_flow/docker/compose/docker-compose.base.yml

# This file must contain valid YAML for merging.
# Even if it defines nothing else, the version key is needed.


# You could add empty services, networks, or volumes keys if desired,
# but just version is enough to clear the 'NoneType' error.
# services: {}
# networks: {}
# volumes: {}